# Generated by Django 5.0.2 on 2024-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
